services:
  - type: keyvalue
    name: orbit-redis
    ipAllowList: []

  - type: web
    name: orbit-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && daphne -b 0.0.0.0 -p $PORT core.asgi:application
    healthCheckPath: /api/health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: REDIS_HOST
        fromService:
          type: keyvalue
          name: orbit-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: keyvalue
          name: orbit-redis
          property: port
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
