# Generated by Django 4.2.11 on 2026-03-27 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_servers', to=settings.AUTH_USER_MODEL),
        ),
    ]
